# Generated by Django 6.0.3 on 2026-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('img', models.ImageField(upload_to='img')),
                ('tg', models.CharField(blank=True, max_length=150, null=True)),
                ('tg_akk', models.CharField(blank=True, max_length=150, null=True)),
                ('insta', models.CharField(blank=True, max_length=150, null=True)),
                ('youtube', models.CharField(blank=True, max_length=150, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=150, null=True)),
                ('github', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
